language: node_js
node_js:
- "stable"
before_script:
- cd src
- npm install -g protractor
- npm install -g http-server
- sudo apt-get install xvfb
- http-server &
- webdriver-manager update --standalone
- webdriver-manager start &
- sleep 5
- npm install -g @angular/cli
script: ng build
after_success: npm run coverage
