= dechat_es6a

image:https://travis-ci.org/Arquisoft/dechat_es6a.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es6a"]
image:https://codecov.io/gh/Arquisoft/dechat_es6a/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es6a"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es6a?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es6a&utm_campaign=Badge_Grade"]

== Authors

Cristian Lado González

Jorge Álvarez Fidalgo

Othmane Bakhtaoui

Mª Isabel Fernández Pérez

Álvaro González Carracedo

== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/docs[src/docs].

To generate the documentation, you have to install gulp:

----
npm install gulp
----

Once installed, running gulp generates the documentation:

----
gulp
----

== Compile and run

To run the application, you have to install http-server:

----
 npm install http-server -g
----

Then, run the command

----
http-server
----

It will shows some IP addresses where the application will be available.

== Testing

There are some simple Unit tests at:
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/test[src/test].

There are also some
 https://cucumber.io/[Cucumber based tests]
 with a simple user story defined at:
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/test/resources/features[src/test/resources/features].

To run tests execute:

----
mvn test
----

== Site documentation

The https://github.com/Arquisoft/dechat_es6a/tree/master/pom.xml[pom.xml] file
 has also been configured to generate site project documentation running:

----
mvn site
----











