= dechat_es6a

image:https://travis-ci.org/Arquisoft/dechat_es6a.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_es6a"]
image:https://codecov.io/gh/Arquisoft/dechat_es6a/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_es6a"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_es6a?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_es6a&utm_campaign=Badge_Grade"]

== Authors

Cristian Lado González

Jorge Álvarez Fidalgo

Othmane Bakhtaoui

Mª Isabel Fernández Pérez

Álvaro González Carracedo

Jorge Iturrioz del Vigo

== Getting started

First of all, you have to install npm (see how to do it below):

=== Windows

- Download the Windows installer from the http://nodejs.org/[Nodes.js® web site]
- Run the installer you've just downloaded
- Follow the prompts in the installer
- Restart your computer

=== Mac

Before installing npm, we need to install two other applications:

* XCode: Apple's XCode development software is used to build Mac and iOS apps, but it also includes the tools you need to compile software for use on your Mac. You can get it here at https://itunes.apple.com/us/app/xcode/id497799835?mt=12[Apple App Store]

* Homebrew: Homebrew is a package manager for the Mac — it makes installing most open source sofware (like Node) much easier. To install Homebrew just open Terminal and type:

----
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

You'll see messages in the Terminal explaining what you need to do to complete the installation process.
Once homebrew is installed, you have to do type the following:

----
brew install node
----
And there we go

=== Linux

You need to install a number of dependancies before you can install Node.js and NPM:

* For Ubuntu or Debian-based Linux distributions, run the following command in your terminal:

----
sudo apt-get install build-essential curl git m4 ruby texinfo libbz2-dev libcurl4-openssl-dev libexpat-dev libncurses-dev zlib1g-dev
----

* For Fedora based Linux distributions run the following command in your terminal application:

----
sudo yum groupinstall 'Development Tools' && sudo yum install curl git m4 ruby texinfo bzip2-devel curl-devel expat-devel ncurses-devel zlib-devel
----

Homebrew:
To install Homebrew for Linux, open your terminal application and paste in the command:
----
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/linuxbrew/go/install)"
----

Once Linuxbrew is installed, you’ll need add the following 3 lines to your .bashrc or .zshrc file:

----
export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
----

Once everything is done, you have to open your terminal and type:
----
brew install node
----
And that's it.

== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/docs[src/docs].

To generate the documentation, you have to install gulp:

----
npm install gulp
----

Once installed, running gulp generates the documentation:

----
gulp
----

== Compile and run

To run the application, you have to install http-server:

----
 npm install http-server -g
----

And then execute the following command:

----
 npm run build:web
----

Lastly, run the command:

----
http-server
----

It will shows some IP addresses where the application will be available.

== Testing

There are some simple Unit tests at:
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/test[src/test].

There are also some
 https://cucumber.io/[Cucumber based tests]
 with a simple user story defined at:
 https://github.com/Arquisoft/dechat_es6a/tree/master/src/test/resources/features[src/test/resources/features].

To run tests execute:

----
npm test
----

== Site documentation

The https://github.com/Arquisoft/dechat_es6a/tree/master/pom.xml[pom.xml] file
 has also been configured to generate site project documentation. To do this, it is necessary to install https://maven.apache.org/[Maven], and then, run the following command:

----
mvn site
----











